import React, { useState, useEffect } from 'react';
import { SequenceResult, AlbumData, SequencedTrack } from '../types';
import { PlayCircle, RefreshCw, Music2, ListMusic, Edit2, Check, X, Download, FileJson, FileText, FileSpreadsheet } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface ResultsViewProps {
  result: SequenceResult;
  albumData: AlbumData;
  onReset: () => void;
}

export const ResultsView: React.FC<ResultsViewProps> = ({ result, albumData, onReset }) => {
  const [tracks, setTracks] = useState<SequencedTrack[]>(result.sequencedTracks);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [editForm, setEditForm] = useState<SequencedTrack | null>(null);

  useEffect(() => {
    setTracks(result.sequencedTracks);
  }, [result]);

  const startEditing = (index: number, track: SequencedTrack) => {
    setEditingIndex(index);
    setEditForm({ ...track });
  };

  const cancelEditing = () => {
    setEditingIndex(null);
    setEditForm(null);
  };

  const saveEditing = () => {
    if (editForm && editingIndex !== null) {
      const newTracks = [...tracks];
      newTracks[editingIndex] = editForm;
      setTracks(newTracks);
      setEditingIndex(null);
      setEditForm(null);
    }
  };

  const handleInputChange = (field: keyof SequencedTrack, value: string) => {
    if (editForm) {
      setEditForm({ ...editForm, [field]: value });
    }
  };

  const getSafeFilename = (ext: string) => {
    return `${albumData.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_sequence.${ext}`;
  };

  const handleExportTxt = () => {
    const txtContent = `ALBUM SEQUENCE REPORT
----------------------------------------
Album:  ${albumData.title}
Artist: ${albumData.artist}
Genre:  ${albumData.genre}
----------------------------------------

ANALYSIS
${result.albumAnalysis}

NARRATIVE ARC
${result.narrativeArc}

----------------------------------------
TRACKLIST SEQUENCE
----------------------------------------
${tracks.map(t => 
`
${t.trackNumber.toString().padStart(2, '0')}. ${t.title}
    Reasoning:  ${t.reasoning}
    Transition: ${t.transitionNote || 'N/A'}
`).join('')}
----------------------------------------
Generated by SonicSequence AI
`;

    const blob = new Blob([txtContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getSafeFilename('txt');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportJson = () => {
    const exportPayload = {
      album: {
        title: albumData.title,
        artist: albumData.artist,
        genre: albumData.genre,
      },
      analysis: result.albumAnalysis,
      narrative: result.narrativeArc,
      tracks: tracks
    };
    
    const jsonString = JSON.stringify(exportPayload, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getSafeFilename('json');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportCsv = () => {
    const headers = ['Track Number', 'Title', 'Reasoning', 'Transition Note'];
    const rows = tracks.map(t => [
      t.trackNumber,
      `"${t.title.replace(/"/g, '""')}"`,
      `"${t.reasoning.replace(/"/g, '""')}"`,
      `"${(t.transitionNote || '').replace(/"/g, '""')}"`
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getSafeFilename('csv');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => {
    const doc = new jsPDF();
    
    // Brand Colors
    const bgDark = '#09090b'; // Zinc 950 (App Background)
    const bgCard = '#18181b'; // Zinc 900 (App Panel)
    const textLight = '#e4e4e7'; // Zinc 200
    const textMuted = '#a1a1aa'; // Zinc 400
    const primaryColor = '#2563eb'; // Blue 600
    const accentColor = '#3b82f6'; // Blue 500

    // --- HEADER SECTION ---
    // Dark background block
    doc.setFillColor(bgDark);
    doc.rect(0, 0, 210, 55, 'F');

    // Draw Vector Vinyl Disc
    const discX = 28;
    const discY = 28;
    const discRadius = 18;

    // 1. Outer Vinyl (Dark Grey/Black)
    doc.setFillColor('#111111');
    doc.circle(discX, discY, discRadius, 'F');

    // 2. Grooves (Subtle lines)
    doc.setDrawColor('#27272a'); // Zinc 800
    doc.setLineWidth(0.1);
    for (let r = 16; r > 6; r -= 1.5) {
        doc.circle(discX, discY, r, 'S');
    }

    // 3. Label (Primary Color)
    doc.setFillColor(primaryColor);
    doc.circle(discX, discY, 6.5, 'F');

    // 4. Center Hole
    doc.setFillColor('#000000');
    doc.circle(discX, discY, 1, 'F');

    // --- ALBUM INFO ---
    const textStartX = 60;

    // Brand Watermark
    doc.setFontSize(8);
    doc.setTextColor(accentColor);
    doc.setFont("helvetica", "bold");
    doc.text("SONICSEQUENCE REPORT", textStartX, 16);

    // Album Title
    doc.setFontSize(24);
    doc.setTextColor('#ffffff');
    doc.setFont("helvetica", "bold");
    doc.text(albumData.title, textStartX, 27);

    // Artist
    doc.setFontSize(14);
    doc.setTextColor(textMuted);
    doc.setFont("helvetica", "normal");
    doc.text(albumData.artist, textStartX, 34);
    
    // Genre
    doc.setFontSize(10);
    doc.setTextColor(accentColor);
    doc.text(albumData.genre.toUpperCase(), textStartX, 42);

    // --- BODY CONTENT ---
    let yPos = 70;

    // Analysis
    doc.setFontSize(12);
    doc.setTextColor(bgCard); // Dark text for body on white paper
    doc.setFont("helvetica", "bold");
    doc.text("Album Analysis", 14, yPos);
    
    yPos += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor('#3f3f46'); // Zinc 700
    
    const splitAnalysis = doc.splitTextToSize(result.albumAnalysis, 180);
    doc.text(splitAnalysis, 14, yPos);
    
    yPos += (splitAnalysis.length * 4.5) + 10;

    // Narrative Arc
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(bgCard);
    doc.text("Narrative Arc", 14, yPos);
    
    yPos += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor('#52525b'); // Zinc 600
    
    const splitNarrative = doc.splitTextToSize(result.narrativeArc, 180);
    doc.text(splitNarrative, 14, yPos);
    
    yPos += (splitNarrative.length * 4.5) + 15;

    // --- TRACKS TABLE ---
    // Robustly handle autoTable ESM export structure
    const autoTableFn = (autoTable as any).default || autoTable;
    
    if (typeof autoTableFn === 'function') {
        autoTableFn(doc, {
          startY: yPos,
          head: [['#', 'Title', 'Sequencing Logic', 'Flow']],
          body: tracks.map(t => [
            t.trackNumber.toString().padStart(2, '0'),
            t.title,
            t.reasoning,
            t.transitionNote || '-'
          ]),
          theme: 'grid',
          headStyles: { 
              fillColor: bgCard, 
              textColor: '#ffffff', 
              fontStyle: 'bold',
              lineWidth: 0
          },
          styles: { 
              fontSize: 9, 
              cellPadding: 4, 
              overflow: 'linebreak',
              textColor: '#333333',
              lineColor: '#e5e7eb',
              lineWidth: 0.1
          },
          columnStyles: {
            0: { cellWidth: 12, halign: 'center', fontStyle: 'bold', textColor: primaryColor },
            1: { cellWidth: 45, fontStyle: 'bold' },
            2: { cellWidth: 85 },
            3: { cellWidth: 40, fontStyle: 'italic', textColor: '#555555' }
          },
          alternateRowStyles: { fillColor: '#f8fafc' }
        });
    } else {
        console.error("Failed to load autoTable function for PDF generation.");
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor('#9ca3af');
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text('Generated by SonicSequence AI', 14, 285);
        doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
    }
    
    doc.save(getSafeFilename('pdf'));
  };

  return (
    <div className="w-full max-w-4xl mx-auto animate-fade-in pb-12">
      
      {/* Album Header */}
      <div className="flex flex-col md:flex-row gap-10 mb-10 items-start border-b border-white/5 pb-8">
        {/* Virtual Vinyl Cover - Enhanced with Disc */}
        <div className="relative w-40 h-40 flex-shrink-0 mx-auto md:mx-0 animate-fade-in-up z-10 group">
          {/* Sleeve */}
          <div className="absolute inset-0 bg-zinc-800 rounded shadow-2xl border border-zinc-700 z-20 flex flex-col items-center justify-center overflow-hidden">
             <div className="absolute inset-0 bg-gradient-to-br from-zinc-800 to-zinc-900"></div>
             <div className="z-10 flex flex-col items-center">
                <span className="text-zinc-500 font-mono text-[10px] font-bold tracking-widest mb-1">SONIC</span>
                <div className="w-8 h-1 bg-primary-500 rounded-full mb-1"></div>
                <span className="text-zinc-600 font-mono text-[10px] font-bold tracking-widest uppercase">Sequence</span>
             </div>
             <div className="absolute bottom-2 right-2 text-zinc-700">
                <Music2 size={16} />
             </div>
          </div>
          
          {/* Vinyl Disc - Sliding Out/Spinning */}
          <div className="absolute top-1 left-1 w-[152px] h-[152px] rounded-full bg-[#050505] shadow-2xl z-10 group-hover:translate-x-16 transition-transform duration-700 ease-out flex items-center justify-center">
             {/* Grooves */}
             <div className="absolute inset-0 rounded-full vinyl-groove opacity-80"></div>
             {/* Reflection */}
             <div className="absolute inset-0 rounded-full bg-gradient-to-tr from-white/5 to-transparent pointer-events-none"></div>
             {/* Label */}
             <div className="w-16 h-16 rounded-full bg-primary-600 flex items-center justify-center shadow-inner border-[3px] border-zinc-900/50 animate-[spin_3s_linear_infinite]">
                <div className="text-[6px] font-bold text-primary-900 uppercase tracking-tighter text-center leading-none">
                  Sonic<br/>Sequence
                </div>
                <div className="absolute w-1.5 h-1.5 bg-black rounded-full"></div>
             </div>
          </div>
        </div>

        <div className="flex-grow space-y-4 opacity-0 animate-fade-in-up z-0 pl-4 md:pl-0" style={{ animationDelay: '150ms' }}>
          <div>
            <h1 className="text-3xl font-bold text-white mb-2 tracking-tight">
              {albumData.title}
            </h1>
            <p className="text-primary-400 font-mono text-sm uppercase tracking-wider mb-4">{albumData.artist}</p>
            <p className="text-zinc-400 font-light text-base leading-relaxed max-w-2xl">
              {result.albumAnalysis}
            </p>
          </div>
          
          <div className="bg-zinc-900/50 p-4 rounded border-l-2 border-primary-500">
            <h4 className="text-zinc-500 text-[10px] font-bold uppercase tracking-widest mb-1">Narrative Arc</h4>
            <p className="text-zinc-300 italic text-sm font-medium">{result.narrativeArc}</p>
          </div>
        </div>
      </div>

      {/* Tracklist */}
      <div className="glass-panel rounded-xl overflow-hidden shadow-2xl border-zinc-800 opacity-0 animate-fade-in-up" style={{ animationDelay: '300ms' }}>
        <div className="bg-zinc-900/80 px-6 py-3 border-b border-zinc-800 flex items-center justify-between">
           <div className="flex items-center gap-2">
             <ListMusic className="text-zinc-500" size={16}/>
             <h3 className="font-semibold text-zinc-300 text-sm uppercase tracking-widest">Master Sequence</h3>
           </div>
           <span className="text-xs text-zinc-600 font-mono">{tracks.length} TRACKS</span>
        </div>

        <div className="divide-y divide-zinc-800/50">
          {tracks.map((track, idx) => {
            const isEditing = editingIndex === idx;

            return (
              <div 
                key={idx} 
                className={`p-5 transition-all duration-300 ease-out group border-l-2 border-transparent ${isEditing ? 'bg-zinc-800/30 border-primary-500 translate-x-2 shadow-xl shadow-black/40' : 'hover:bg-white/5 hover:border-primary-500 hover:translate-x-2 hover:shadow-lg hover:shadow-black/20'} opacity-0 animate-fade-in-up`}
                style={{ animationDelay: `${(idx * 50) + 400}ms` }}
              >
                {isEditing && editForm ? (
                  // EDIT MODE
                  <div className="flex flex-col gap-4 animate-fade-in pl-2">
                     <div className="flex items-center gap-4">
                        <span className="font-mono text-lg text-primary-400 font-bold">
                          {track.trackNumber.toString().padStart(2, '0')}
                        </span>
                        <input
                          type="text"
                          value={editForm.title}
                          onChange={(e) => handleInputChange('title', e.target.value)}
                          className="bg-zinc-900 border border-zinc-700 rounded px-3 py-1 text-white focus:outline-none focus:border-primary-500 flex-grow"
                        />
                     </div>
                     <textarea
                        value={editForm.reasoning}
                        onChange={(e) => handleInputChange('reasoning', e.target.value)}
                        className="bg-zinc-900 border border-zinc-700 rounded px-3 py-2 text-zinc-300 text-sm focus:outline-none focus:border-primary-500 w-full h-20"
                     />
                     <input
                        type="text"
                        value={editForm.transitionNote || ''}
                        onChange={(e) => handleInputChange('transitionNote', e.target.value)}
                        placeholder="Transition Note"
                        className="bg-zinc-900 border border-zinc-700 rounded px-3 py-1 text-zinc-400 text-xs focus:outline-none focus:border-primary-500 w-full"
                     />
                     <div className="flex gap-2 justify-end mt-2">
                       <button onClick={cancelEditing} className="p-2 text-zinc-500 hover:text-white"><X size={16}/></button>
                       <button onClick={saveEditing} className="p-2 bg-primary-600 text-white rounded hover:bg-primary-500"><Check size={16}/></button>
                     </div>
                  </div>
                ) : (
                  // VIEW MODE
                  <div className="flex gap-6 items-start relative">
                    <div className="font-mono text-xl text-zinc-600 font-bold pt-1 select-none">
                       {track.trackNumber.toString().padStart(2, '0')}
                    </div>
                    <div className="flex-grow space-y-2">
                       <div className="flex justify-between items-start">
                          <h4 className="text-lg font-medium text-white">{track.title}</h4>
                          <button 
                            onClick={() => startEditing(idx, track)}
                            className="opacity-0 group-hover:opacity-100 transition-opacity text-zinc-600 hover:text-primary-400"
                          >
                            <Edit2 size={14} />
                          </button>
                       </div>
                       <p className="text-zinc-400 text-sm leading-relaxed border-l-2 border-zinc-800 pl-3">
                         {track.reasoning}
                       </p>
                       {track.transitionNote && (
                         <div className="flex items-center gap-2 text-xs text-zinc-500 mt-2 italic">
                           <span className="w-1.5 h-1.5 rounded-full bg-zinc-700"></span>
                           {track.transitionNote}
                         </div>
                       )}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Export Actions */}
      <div className="flex flex-wrap justify-center gap-4 mt-10 opacity-0 animate-fade-in-up" style={{ animationDelay: '800ms' }}>
        <button onClick={handleExportTxt} className="flex items-center gap-2 px-5 py-2.5 bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border border-zinc-800 rounded-md transition-all text-sm hover:border-zinc-600">
           <FileText size={16} /> Text File
        </button>
        <button onClick={handleExportJson} className="flex items-center gap-2 px-5 py-2.5 bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border border-zinc-800 rounded-md transition-all text-sm hover:border-zinc-600">
           <FileJson size={16} /> JSON
        </button>
        <button onClick={handleExportCsv} className="flex items-center gap-2 px-5 py-2.5 bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border border-zinc-800 rounded-md transition-all text-sm hover:border-zinc-600">
           <FileSpreadsheet size={16} /> CSV
        </button>
        <button onClick={handleExportPdf} className="flex items-center gap-2 px-6 py-2.5 bg-white text-black hover:bg-zinc-200 font-semibold rounded-md transition-all text-sm shadow-lg shadow-white/10">
           <Download size={16} /> Export PDF
        </button>
      </div>

       <div className="text-center mt-16 opacity-0 animate-fade-in" style={{ animationDelay: '1000ms' }}>
          <button 
            onClick={onReset}
            className="text-zinc-500 hover:text-white text-xs uppercase tracking-widest flex items-center gap-2 mx-auto transition-colors"
          >
            <RefreshCw size={12} /> Start New Project
          </button>
      </div>

    </div>
  );
};